# Mantle reth only (same as basic.yml but node_type: reth only)
name: Transfer-only (Mantle Reth)
description: Basic transfer benchmark for Mantle reth only.

payloads:
  - name: Transfer-only execution speed
    id: transfer-only
    type: transfer-only

benchmarks:
  - variables:
      - type: payload
        value: transfer-only
      - type: node_type
        values:
          - reth
      - type: num_blocks
        value: 10
      - type: gas_limit
        values:
          - 20000000
          - 30000000
          - 60000000
          - 90000000
